### ISSUE TITLE
undefined constant CURLOPT_SSL_ENABLE_ALPN

### ISSUE THREAD

**Issue by vukbgit** [taocomp/php-sdicoop-client#2]
innanzitutto complimenti per l'ottimo lavoro, vi segnalo che nella classe Client viene alzata l'eccezione _Use of undefined constant CURLOPT_SSL_ENABLE_ALPN - assumed 'CURLOPT_SSL_ENABLE_ALPN' (this will throw an Error in a future version of PHP)_ con le versioni:
PHP: 7.2.6
cUrl: curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3

Come suggerito in un [post sul forum.italia.it](https://forum.italia.it/t/sdicoop-configurazione-php-soapclient-soapserver-apache-per-invio-e-ricezione-di-test/5528/85) ho risolto sostituendo la costante con il valore numerico __226__

**Comment by aded** [comment]
> innanzitutto complimenti per l'ottimo lavoro, vi segnalo che nella classe Client viene alzata l'eccezione _Use of undefined constant CURLOPT_SSL_ENABLE_ALPN - assumed 'CURLOPT_SSL_ENABLE_ALPN' (this will throw an Error in a future version of PHP)_ con le versioni:
> PHP: 7.2.6
> cUrl: curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
> 
> Come suggerito in un [post sul forum.italia.it](https://forum.italia.it/t/sdicoop-configurazione-php-soapclient-soapserver-apache-per-invio-e-ricezione-di-test/5528/85) ho risolto sostituendo la costante con il valore numerico **226**

Thanks :-)
