### ISSUE TITLE
Future composer require taocomp/php-sdicoop-client

### ISSUE THREAD

**Issue by MwSpaceLLC** [taocomp/php-sdicoop-client#3]
Ciao ancora Ale*!

Senti ma se aggiungessi anche questa distro su https://packagist.org/ ?
Così potremmo scaricare e gestire aggiornamenti tramite composer require taocomp/php-sdicoop-client =)

*ricorda che lasciamo il tuo nome su i Credits del portale 🥇

**Comment by aded** [comment]
Già in programma, anche per php-sdicoop-server, ma devo sistemare i tests e pusharli.
Stay tuned!
